// ui/components/ct-stats.tsx
"use client";

interface CtStatsRow {
    log_id: number;
    max_timestamp: string;
    total: number;
}

interface CtStatsProps {
    stats: CtStatsRow[];
}

export default function CtStats({ stats }: CtStatsProps) {
    return (
        <div className="space-y-3 pt-4">
            <p className="mb-4 font-bold">Statistics</p>
            <div className="overflow-x-auto">
                <table className="text-xs leading-tight font-mono">
                    <thead>
                        <tr
                            className="border-b"
                            style={{ borderColor: "var(--border)" }}
                        >
                            <th
                                className="text-left py-1 pr-4 font-medium"
                                style={{ color: "var(--muted-foreground)" }}
                            >
                                Log
                            </th>
                            <th
                                className="text-left py-1 pr-4 font-medium"
                                style={{ color: "var(--muted-foreground)" }}
                            >
                                Latest (UTC)
                            </th>
                            <th
                                className="text-right py-1 font-medium"
                                style={{ color: "var(--muted-foreground)" }}
                            >
                                Total
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {stats.map((row, index) => (
                            <tr
                                key={row.log_id}
                                className="hover:bg-opacity-50"
                                style={{
                                    color: "var(--foreground)",
                                }}
                            >
                                <td className="py-0.5 pr-4">
                                    {row.log_id}
                                </td>
                                <td className="py-0.5 pr-4">
                                    {row.max_timestamp}
                                </td>
                                <td className="py-0.5 text-right">
                                    {row.total.toLocaleString()}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

// ui/src/lib/components/CtStats.svelte
<script lang="ts">
  interface CtStatsRow {
    log_id: number;
    max_timestamp: string;
    total: number;
  }

  let { stats }: { stats: CtStatsRow[] } = $props();
</script>

<div>
  <h2 class="mb-4 text-lg font-semibold">Certificate Transparency Log Statistics</h2>
  <div class="overflow-x-auto">
    <table class="w-full text-xs">
      <thead>
        <tr class="border-b border-gray-700">
          <th class="p-2 text-left">Log ID</th>
          <th class="p-2 text-left">Latest Entry</th>
          <th class="p-2 text-left">Total Entries</th>
        </tr>
      </thead>
      <tbody>
        {#each stats as stat (stat.log_id)}
          <tr class="border-b border-gray-800 hover:bg-gray-900">
            <td class="p-2 font-mono">{stat.log_id}</td>
            <td class="p-2 font-mono">{stat.max_timestamp}</td>
            <td class="p-2 font-mono">{stat.total.toLocaleString()}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>
